UI/Models/ErrorViewModel.cs
using System;

namespace UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UI/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Models
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
    }
}

UI/Models/StudentGrade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Models
{
    public class StudentGrade
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int SubjectId { get; set; }
        public int Grade { get; set; }
        public string SubjectName { get; set; }
    }
}

UI/Models/StudentGradeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace UI.Models
{
    public class StudentGradeModel
    {
        public Student student {get;set;}
        public IEnumerable<StudentGrade> student_grade_list { get; set; }
        public bool Empty
        {
            get
            {
                return student_grade_list == null || student_grade_list.ToList().Count == 0;
            }
        }
    }
}

UI/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DapperStoreProcedureCRUD.Model
{
    public class Subject
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using UI.Models;

namespace UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

UI/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using UI.Models;
using UI.Service;

namespace UI.Controllers
{
    public class StudentController : Controller
    {
        private readonly IClientService _client_service;

        public IActionResult Index()
        {
            return View();
        }
        public StudentController(IClientService clientService)
        {
            _client_service = clientService;
        }
        [HttpGet]
        public async Task<ActionResult> GetAllStudents()
        {
            var response = await _client_service.GetAll<Student>("/api/Student");
            return new OkObjectResult(response);
        }
        [HttpGet]
        public async Task<ActionResult> GetStudentById(int studentId)
        {
            var response = await _client_service.GetById<Student>("/api/Student/"+studentId);
            return new OkObjectResult(response);
        }
        [HttpDelete]
        public async Task<ActionResult> DeleteStudent(int studentId)
        {
            var response = await _client_service.Delete("/api/Student/" + studentId);
            if (response)
                return Ok("delete successfully");
            return NotFound();
        }
        [HttpPost]
        public async Task<ActionResult> AddOrUpdate(Student student)
        {
            if (!ModelState.IsValid)
            {
                return View(student);
            }
            if (student.Id == 0)
            {
                bool create_response = await _client_service.Post("/api/Student", student);
                return create_response ? View() : BadRequest();
            }
            bool update_response = await _client_service.Put("/api/Student/" + student.Id, student);
            return update_response ? View() : BadRequest();
        }
        public async Task<ActionResult> Detail(int studentId)
        {
            var student = await _client_service.GetById<Student>("/api/Student/" + studentId); ;
            var student_grade_list = await _client_service.GetDataListById<StudentGrade>("/api/StudentGrade/" + studentId);
            var student_grade_model = new StudentGradeModel
            {
                student = student,
                student_grade_list = student_grade_list
            };
            return View(student_grade_model);
        }
    }
}

UI/Controllers/SubjectController.cs
using DapperStoreProcedureCRUD.Model;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UI.Service;

namespace UI.Controllers
{
    public class SubjectController : Controller
    {
        private readonly IClientService _client_service;

        public IActionResult Index()
        {
            return View();
        }
        public SubjectController(IClientService clientService)
        {
            _client_service = clientService;
        }
        [HttpGet]
        public async Task<ActionResult> GetAllSubjects()
        {
            var response = await _client_service.GetAll<Subject>("/api/Subject");
            return new OkObjectResult(response);
        }
        [HttpGet]
        public async Task<ActionResult> GetSubjectById(int subjectId)
        {
            var response = await _client_service.GetById<Subject>("/api/Subject/" + subjectId);
            return new OkObjectResult(response);
        }
        [HttpDelete]
        public async Task<ActionResult> DeleteSubject(int subjectId)
        {
            var response = await _client_service.Delete("/api/Subject/" + subjectId);
            if (response)
                return Ok("delete successfully");
            return NotFound();
        }
        [HttpPost]
        public async Task<ActionResult> AddOrUpdate(Subject subject)
        {
            if (!ModelState.IsValid)
            {
                return View(subject);
            }
            if (subject.Id == 0)
            {
                bool create_response = await _client_service.Post("/api/Subject", subject);
                return create_response ? View() : BadRequest();
            }
            bool update_response = await _client_service.Put("/api/Subject/" + subject.Id, subject);
            return update_response ? View() : BadRequest();
        }
    }
}

UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="Index">Subject</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

UI/Views/Student/Detail.cshtml
@{
    ViewData["Title"] = "Student Grade";
}
@model StudentGradeModel
<script src="~/lib/jquery/dist/jquery.js"></script>
<h1 class="text-danger">@ViewData["Title"]</h1>
<h3> Name :  @Model.student.Name</h3>
<br>
<h5> Id : @Model.student.Id</h5>
<table id="StudentGradeTable" class="table table-sm table-striped table-bordered m-2">
    <thead>
        <tr>
            <th> Id </th>
            <th> Subject </th>
            <th> Grade </th>
        </tr>
    </thead>
    <tbody>
        @if (!@Model.Empty)
        {
            @foreach (var item in @Model.student_grade_list)
            {
                <tr class="text-center font-weight-bold">
                    <td>@item.Id</td>
                    <td>@item.SubjectName</td>
                    <td>@item.Grade</td>
                </tr>
            }
        }
    </tbody>
</table>

UI/Views/Student/Index.cshtml
@{
    ViewData["Title"] = "Student List";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<h1 class="display-4">@ViewData["Title"]</h1>
<h3> Manage Student </h3>
<div class=" form-group">
    <label for="Id">Id: (0 to add)</label>
    <input id="StudentId" class="form-control" name="Id" value="0" type="number"/>
</div>
<div class=" form-group">
    <label for="Name">Name:</label>
    <input id="StudentName" class="form-control" name="Name" type="text"/>
</div>
<div class=" form-group">
    <label for="Class">Class:</label>
    <input id="StudentClass" class="form-control" name="Class" type="text"/>
</div>
<div class="text-center">
    <button id="create" class="btn btn-sm btn-primary" onclick="SaveStudent();"> Save </button>
</div>

<button onclick="GetStudentList();" class="btn btn-primary"> Load</button>
<br>

<h2> Student List</h2>
<table id="StudentTable" class="table table-sm table-striped table-bordered m-2">
    <thead>
        <tr>
            <th> Student ID </th>
            <th> Student Name </th>
            <th> Student Class </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<script>
    $(document).ready(function () {
        GetStudentList();
    });

    function GetStudentList() {
        $.getJSON("Student/GetAllStudents", function (response) {
            console.log(response);
            $("#StudentTable tbody tr").remove();
            $.map(response, function (item) {
                $("#StudentTable tbody").append(
                    "<tr>" +
                    "<td>" + item.id + "</td>" +
                    "<td> <a href='Student/Detail?studentId=" + item.id + "'>" + item.name + "</a></td>" +
                    "<td>" + item.class + "</td>" +
                    "<td>" +
                    "<button class='btn-success' onclick='Edit(" + item.id + ");' style='margin-right:5px;'> Edit </button>" +
                    "<button class='btn-danger' onclick='Delete(" + item.id + ");'> Delete </button>" +
                    "</td>" +
                    "</tr>"
                );
            })
        });
    }
    function Delete(id) {
        if (id > 0) {
            $.ajax({
                url: "Student/DeleteStudent",
                type: "DELETE",
                data: { "studentId": id },
                success: function (success) {
                    GetStudentList();
                },
                error: function (ex) {
                    console.log(ex.responseText);
                }
            });
        }
    }
    function Edit(id) {
        if (id > 0) {
            $.getJSON("Student/GetStudentById?studentId=" + id,
                function (response) {
                    $("#StudentId").val(response.id);
                    $("#StudentName").val(response.name);
                    $("#StudentClass").val(response.class);
                });
        }
    }
    function SaveStudent() {
        var student = {
            Id: $("#StudentId").val(),
            Name: $("#StudentName").val(),
            Class: $("#StudentClass").val()
        };
        $.post("Student/AddOrUpdate", student)
            .always(function () {
                GetStudentList();
            });
    }
</script>

UI/Views/Subject/Index.cshtml
@{
    ViewData["Title"] = "Subject List";
}
<script src="~/lib/jquery/dist/jquery.js"></script>
<h1 class="display-4">@ViewData["Title"]</h1>
<h3> Manage Subject </h3>
<div class=" form-group">
    <label for="Id">Id: (0 to add)</label>
    <input id="SubjectId" class="form-control" name="Id" value="0" type="number" />
</div>
<div class=" form-group">
    <label for="Name">Name:</label>
    <input id="SubjectName" class="form-control" name="Name" type="text" />
</div>
<div class="text-center">
    <button id="create" class="btn btn-sm btn-primary" onclick="SaveSubject();"> Save </button>
</div>

<button onclick="GetSubjectList();" class="btn btn-primary"> Load</button>
<br>

<h2> Subject List</h2>
<table id="SubjectTable" class="table table-sm table-striped table-bordered m-2">
    <thead>
        <tr>
            <th> Subject ID </th>
            <th> Subject Name </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
<script>
    $(document).ready(function () {
        GetSubjectList();
    });

    function GetSubjectList() {
        $.getJSON("Subject/GetAllSubjects", function (response) {
            console.log(response);
            $("#SubjectTable tbody tr").remove();
            $.map(response, function (item) {
                $("#SubjectTable tbody").append(
                    "<tr>" +
                    "<td>" + item.id + "</td>" +
                    "<td>" + item.name + "</td>" +
                    "<td>" +
                    "<button class='btn-success' onclick='Edit(" + item.id + ");' style='margin-right:5px;'> Edit </button>" +
                    "<button class='btn-danger' onclick='Delete(" + item.id + ");'> Delete </button>" +
                    "</td>" +
                    "</tr>"
                );
            })
        });
    }
    function Delete(id) {
        if (id > 0) {
            $.ajax({
                url: "Subject/DeleteSubject",
                type: "DELETE",
                data: { "SubjectId": id },
                success: function (success) {
                    GetSubjectList();
                },
                error: function (ex) {
                    console.log(ex.responseText);
                }
            });
        }
    }
    function Edit(id) {
        if (id > 0) {
            $.getJSON("Subject/GetSubjectById?SubjectId=" + id,
                function (response) {
                    $("#SubjectId").val(response.id);
                    $("#SubjectName").val(response.name);
                });
        }
    }
    function SaveSubject() {
        var Subject = {
            Id: $("#SubjectId").val(),
            Name: $("#SubjectName").val()
        };
        $.post("Subject/AddOrUpdate", Subject)
            .always(function () {
                GetSubjectList();
            });
    }
</script>